#! /bin/bash


#get the base dir/ platform
echo "Who are we hacking today?"
read platform

# get machine name that we're hacking
echo "and the machine?"
read machine_name

#make reporting dirs and setup obsidian
reporting_base_dir=~/Workspace/Reporting/${platform}/${machine_name}/

if [ ! -d $reporting_base_dir ]; then
  mkdir -p $reporting_base_dir;
fi

if [ ! -d $reporting_base_dir/enum ]; then
  mkdir -p $reporting_base_dir/enum;
  mkdir -p $reporting_base_dir/enum/internal;
  mkdir -p $reporting_base_dir/enum/external;
fi

#copy all defauts to folder for obsidian
cp -r obsidian/* $reporting_base_dir

#create defaults for auto scanning
hacking_base_dir=~/Workspace/${platform}/boxes/${machine_name}/

#make hacking dirs
mkdir -p ~/Workspace/${platform}/boxes/${machine_name}

if [ ! -d $hacking_base_dir ]; then
  mkdir -p $hacking_base_dir;
fi

#enum, exploit, loot, privesc
if [ ! -d $hacking_base_dir/enum ]; then
  mkdir -p $hacking_base_dir/enum;
  mkdir -p $hacking_base_dir/exploit;
  mkdir -p $hacking_base_dir/loot;
  mkdir -p $hacking_base_dir/privesc;
fi

# clear the command prompt
clear 

#switch console to new location
cd $hacking_base_dir

figlet -f slant "Lets go!"

echo "..............................."

# get machine name that we're hacking
echo "Whats the IP?"
read ip_addr

#run autorecon
autorecon ${ip_addr}


#open obsidian
#yes | open "obsidian://open?vault=Reporting" &
